Update checkin.yml

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -15,11 +15,14 @@ jobs:
 
     - name: "npm run test"
       run: npm run test
+      
+    - name: "TEST ACTION"
+      uses: ibakshay/action-template@v1-release
 
-    - name: "check for uncommitted changes"
+    #- name: "check for uncommitted changes"
       # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
-      run: |
-        git diff --exit-code --stat -- . ':!node_modules' \
-        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
-                 "and check in all changes" \
-            && exit 1)
+     # run: |
+      #  git diff --exit-code --stat -- . ':!node_modules' \
+       # || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
+        #         "and check in all changes" \
+         #   && exit 1)
